[package]
name = "mandel_zoom"
version = "0.1.0"
authors = ["Jean d'Arc <darc.void@googlemail.com>"]
edition = "2018"

[dependencies]
palette = "0.5.0"
num = "0.1.34"
image = "0.13.0"
rayon = "0.4.0"
gtk = "0.9.2"
gdk = "0.13.2"
gdk-pixbuf = "0.9.0"
gio = "0.9.1"
glib = "0.10.3"

